In [1]:
import pandas as pd
df = pd.read_csv('C:/Users/icorw\iCloudDrive/DST9/data_sf.csv')

#### Задание 2.8.1

In [5]:
df.groupby('Position')[['Wage', 'Value']].mean().sort_values(['Value'], ascending=False)

                   Wage         Value
Position
LF         75125.000000  2.736250e+07
RF        119000.000000  2.636583e+07
LAM        61000.000000  1.324583e+07
RAM        11800.000000  8.345000e+06
LS         15421.487603  5.848430e+06
LCM        13497.854077  4.318090e+06
RCM        13504.166667  4.217604e+06
RS         13482.456140  3.645833e+06
LW         12169.421488  3.603099e+06
RW         13822.784810  3.495738e+06
LDM        10243.243243  3.369459e+06
RCB        11270.334928  3.009055e+06
CAM         8688.783570  2.963199e+06
RDM        11282.608696  2.692717e+06
LCB         9753.056235  2.636516e+06
LM          7472.527473  2.466174e+06
ST          7852.513228  2.157252e+06
RM          6655.352480  2.138734e+06
LWB         5783.333333  1.931333e+06
CF          4862.745098  1.848627e+06
CDM         7121.562952  1.658900e+06
CM          5805.060918  1.617465e+06
RWB         6000.000000  1.555571e+06
GK          5352.833638  1.502502e+06
LB          6083.832335  1.429032e+06
CB          5328.581611  1.321251e+06
RB          5310.126582  1.248940e+06